params ["_pos", "_isFast"];

private ["_typesSlow", "_typesFast", "_unit"];

_typesSlow = [
"GRAD_CivilianZed_rds_schoolteacher_slow",
"GRAD_CivilianZed_rds_Functionary1_slow",
"GRAD_CivilianZed_rds_Functionary2_slow",
"GRAD_CivilianZed_rds_doctor_slow",
"GRAD_CivilianZed_rds_uniform_priest_slow",
"GRAD_CivilianZed_rds_uniform_assistant_slow",
"GRAD_CivilianZed_rds_uniform_Worker1_slow",
"GRAD_CivilianZed_rds_uniform_Worker2_slow",
"GRAD_CivilianZed_rds_uniform_Worker3_slow",
"GRAD_CivilianZed_rds_uniform_Worker4_slow",
"GRAD_CivilianZed_rds_uniform_Woodlander1_slow",
"GRAD_CivilianZed_rds_uniform_Woodlander2_slow",
"GRAD_CivilianZed_rds_uniform_Woodlander3_slow",
"GRAD_CivilianZed_rds_uniform_Woodlander4_slow",
"GRAD_CivilianZed_rds_uniform_Villager1_slow",
"GRAD_CivilianZed_rds_uniform_Villager2_slow",
"GRAD_CivilianZed_rds_uniform_Villager3_slow",
"GRAD_CivilianZed_rds_uniform_Villager4_slow",
"GRAD_CivilianZed_rds_uniform_Profiteer1_slow",
"GRAD_CivilianZed_rds_uniform_Profiteer2_slow",
"GRAD_CivilianZed_rds_uniform_Profiteer3_slow",
"GRAD_CivilianZed_rds_uniform_Profiteer4_slow",
"GRAD_CivilianZed_rds_uniform_citizen1_slow",
"GRAD_CivilianZed_rds_uniform_citizen2_slow",
"GRAD_CivilianZed_rds_uniform_citizen3_slow",
"GRAD_CivilianZed_rds_uniform_citizen4_slow",
"GRAD_CivilianZed_rds_uniform_Rocker1_slow",
"GRAD_CivilianZed_rds_uniform_Rocker2_slow",
"GRAD_CivilianZed_rds_uniform_Rocker3_slow",
"GRAD_CivilianZed_rds_uniform_Rocker4_slow",
"GRAD_CivilianZed_rds_schoolteacher_crawler",
"GRAD_CivilianZed_rds_Functionary1_crawler",
"GRAD_CivilianZed_rds_Functionary2_crawler",
"GRAD_CivilianZed_rds_doctor_crawler",
"GRAD_CivilianZed_rds_uniform_priest_crawler",
"GRAD_CivilianZed_rds_uniform_assistant_crawler",
"GRAD_CivilianZed_rds_uniform_Worker1_crawler",
"GRAD_CivilianZed_rds_uniform_Worker2_crawler",
"GRAD_CivilianZed_rds_uniform_Worker3_crawler",
"GRAD_CivilianZed_rds_uniform_Worker4_crawler",
"GRAD_CivilianZed_rds_uniform_Woodlander1_crawler",
"GRAD_CivilianZed_rds_uniform_Woodlander2_crawler",
"GRAD_CivilianZed_rds_uniform_Woodlander3_crawler",
"GRAD_CivilianZed_rds_uniform_Woodlander4_crawler",
"GRAD_CivilianZed_rds_uniform_Villager1_crawler",
"GRAD_CivilianZed_rds_uniform_Villager2_crawler",
"GRAD_CivilianZed_rds_uniform_Villager3_crawler",
"GRAD_CivilianZed_rds_uniform_Villager4_crawler",
"GRAD_CivilianZed_rds_uniform_Profiteer1_crawler",
"GRAD_CivilianZed_rds_uniform_Profiteer2_crawler",
"GRAD_CivilianZed_rds_uniform_Profiteer3_crawler",
"GRAD_CivilianZed_rds_uniform_Profiteer4_crawler",
"GRAD_CivilianZed_rds_uniform_citizen1_crawler",
"GRAD_CivilianZed_rds_uniform_citizen2_crawler",
"GRAD_CivilianZed_rds_uniform_citizen3_crawler",
"GRAD_CivilianZed_rds_uniform_citizen4_crawler",
"GRAD_CivilianZed_rds_uniform_Rocker1_crawler",
"GRAD_CivilianZed_rds_uniform_Rocker2_crawler",
"GRAD_CivilianZed_rds_uniform_Rocker3_crawler",
"GRAD_CivilianZed_rds_uniform_Rocker4_crawler"
];

_typesFast = [
"GRAD_CivilianZed_rds_schoolteacher_walker",
"GRAD_CivilianZed_rds_Functionary1_walker",
"GRAD_CivilianZed_rds_Functionary2_walker",
"GRAD_CivilianZed_rds_doctor_walker",
"GRAD_CivilianZed_rds_uniform_priest_walker",
"GRAD_CivilianZed_rds_uniform_assistant_walker",
"GRAD_CivilianZed_rds_uniform_Worker1_walker",
"GRAD_CivilianZed_rds_uniform_Worker2_walker",
"GRAD_CivilianZed_rds_uniform_Worker3_walker",
"GRAD_CivilianZed_rds_uniform_Worker4_walker",
"GRAD_CivilianZed_rds_uniform_Woodlander1_walker",
"GRAD_CivilianZed_rds_uniform_Woodlander2_walker",
"GRAD_CivilianZed_rds_uniform_Woodlander3_walker",
"GRAD_CivilianZed_rds_uniform_Woodlander4_walker",
"GRAD_CivilianZed_rds_uniform_Villager1_walker",
"GRAD_CivilianZed_rds_uniform_Villager2_walker",
"GRAD_CivilianZed_rds_uniform_Villager3_walker",
"GRAD_CivilianZed_rds_uniform_Villager4_walker",
"GRAD_CivilianZed_rds_uniform_Profiteer1_walker",
"GRAD_CivilianZed_rds_uniform_Profiteer2_walker",
"GRAD_CivilianZed_rds_uniform_Profiteer3_walker",
"GRAD_CivilianZed_rds_uniform_Profiteer4_walker",
"GRAD_CivilianZed_rds_uniform_citizen1_walker",
"GRAD_CivilianZed_rds_uniform_citizen2_walker",
"GRAD_CivilianZed_rds_uniform_citizen3_walker",
"GRAD_CivilianZed_rds_uniform_citizen4_walker",
"GRAD_CivilianZed_rds_uniform_Rocker1_walker",
"GRAD_CivilianZed_rds_uniform_Rocker2_walker",
"GRAD_CivilianZed_rds_uniform_Rocker3_walker",
"GRAD_CivilianZed_rds_uniform_Rocker4_walker",
"GRAD_CivilianZed_rds_schoolteacher_fast",
"GRAD_CivilianZed_rds_Functionary1_fast",
"GRAD_CivilianZed_rds_Functionary2_fast",
"GRAD_CivilianZed_rds_doctor_fast",
"GRAD_CivilianZed_rds_uniform_priest_fast",
"GRAD_CivilianZed_rds_uniform_assistant_fast",
"GRAD_CivilianZed_rds_uniform_Worker1_fast",
"GRAD_CivilianZed_rds_uniform_Worker2_fast",
"GRAD_CivilianZed_rds_uniform_Worker3_fast",
"GRAD_CivilianZed_rds_uniform_Worker4_fast",
"GRAD_CivilianZed_rds_uniform_Woodlander1_fast",
"GRAD_CivilianZed_rds_uniform_Woodlander2_fast",
"GRAD_CivilianZed_rds_uniform_Woodlander3_fast",
"GRAD_CivilianZed_rds_uniform_Woodlander4_fast",
"GRAD_CivilianZed_rds_uniform_Villager1_fast",
"GRAD_CivilianZed_rds_uniform_Villager2_fast",
"GRAD_CivilianZed_rds_uniform_Villager3_fast",
"GRAD_CivilianZed_rds_uniform_Villager4_fast",
"GRAD_CivilianZed_rds_uniform_Profiteer1_fast",
"GRAD_CivilianZed_rds_uniform_Profiteer2_fast",
"GRAD_CivilianZed_rds_uniform_Profiteer3_fast",
"GRAD_CivilianZed_rds_uniform_Profiteer4_fast",
"GRAD_CivilianZed_rds_uniform_citizen1_fast",
"GRAD_CivilianZed_rds_uniform_citizen2_fast",
"GRAD_CivilianZed_rds_uniform_citizen3_fast",
"GRAD_CivilianZed_rds_uniform_citizen4_fast",
"GRAD_CivilianZed_rds_uniform_Rocker1_fast",
"GRAD_CivilianZed_rds_uniform_Rocker2_fast",
"GRAD_CivilianZed_rds_uniform_Rocker3_fast",
"GRAD_CivilianZed_rds_uniform_Rocker4_fast"
];

if (_isFast) then {
	_grp = creategroup independent;
	_unit = _grp createUnit [selectRandom _typesFast, _pos, [], 0, "NONE"];
	_unit enableDynamicSimulation true;
	_unit setVariable ["RZ_isDemon", false];
	_unit setVariable ["RZ_vehicleClass","RyanZombieC_man_1"];
} else {
	_grp = creategroup independent;
	_unit = _grp createUnit [selectRandom _typesSlow, _pos, [], 0, "NONE"];
	_unit enableDynamicSimulation true;
	_unit setVariable ["RZ_isDemon", false];
	_unit setVariable ["RZ_vehicleClass","RyanZombieC_man_1"];
};